### ISSUE TITLE
problem with npm install

### ISSUE THREAD

**Issue by quangv** [visionmedia/page.js#202]
`npm install page` gives me following errors: `npm-debug.log`

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install', 'page' ]
2 info using npm@1.4.28
3 info using node@v0.10.32
4 error Error: Invalid version: "0.2"
4 error     at Object.module.exports.fixVersionField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:183:13)
4 error     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:30:38
4 error     at Array.forEach (native)
4 error     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:15)
4 error     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:342:33)
4 error     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
4 error     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:331:40
4 error     at evalmachine.<anonymous>:271:14
4 error     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
4 error     at Object.oncomplete (evalmachine.<anonymous>:107:15)
5 error If you need help, you may report this *entire* log,
5 error including the npm and node versions, at:
5 error     <http://github.com/npm/npm/issues>
6 error System Linux 3.13.0-36-generic
7 error command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "page"
8 error cwd /home/quang/dev/nike
9 error node -v v0.10.32
10 error npm -v 1.4.28
11 verbose exit [ 1, true ]
```

**Comment by quangv** [comment]
oops my `package.json` had `  "version": "0.2",` guess npm got upset, needed to be `0.2.0` ... carry on.
