### ISSUE TITLE
Named wildcard routes aren't working

### ISSUE THREAD

**Issue by claydiffrient** [visionmedia/page.js#338]
It seems that named wildcard routes as described in the documentation aren't working as expected.

I wrote this test, and it fails consistently.
```
it('should populate named wildcard params', function (done) {
  page('/blog/post/:path(*)', function (ctx) {
    expect(ctx.params.path).to.equal('/assets/images/image.png');
  });

  page('/blog/post/assets/images/image.png');
});
```

The error that it throws is:
```
SyntaxError: Invalid regular expression: /^\/blog\/post\/(*)(?:\/(?=$))?$/: Nothing to repeat
      at new RegExp (native)
      at tokensToRegExp (node_modules/path-to-regexp/index.js:356:10)
      at stringToRegexp (node_modules/path-to-regexp/index.js:283:12)
      at pathToRegexp (node_modules/path-to-regexp/index.js:389:10)
      at new Route (index.js:451:19)
      at page (index.js:93:19)
      at Context.<anonymous> (test/tests.js:348:11)
```

I'm not super familiar with why this is happening.  I'll put in a PR containing the failing test.  If I get some time to investigate and look into it more I can fix it.

**Comment by woodlandhunter** [comment]
It seems this is due to the changes in path-to-regexp. An asterisk by itself is supported (e.g. `/some/*`) as a special case, but not as part of a named group. The docs should likely be fixed to reflect this. 

You can use `'/blog/post/:path(.*)'`

See https://github.com/pillarjs/path-to-regexp/issues/37#issuecomment-101310166

**Comment by matthewp** [comment]
Yep, we should update the documentation.
